title:             Alp Eren Işık
email:             your-email@example.com
description:       A Blog Theme by Start Bootstrap
author:            Alp Eren Işık
baseurl:           ""
url:               "http://isikerenalp.me"

# Social Profiles
linkedin_username:  alp-eren-isik
github_username:   isikerenalp
dersim_username:   @alperenisik
# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
