title:             Clean Blog
email:             your-email@example.com
description:       A Blog Theme by Start Bootstrap
author:            Alp Eren Işık
baseurl:           ""
url:               "http://isikerenalp.me"

# Social Profiles
github_username:   isikerenalp

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
