title: Blog
description: Alp Eren
author: Alp Eren
github: https://github.com/isikerenalp
about: PauSiber
# disqus_shortname:
google_analytics: UA-149877622-1
avatar_url: /static/img/profile.png

enableTags: true
tagarray: []


social:
    - icon: fa-twitter
      link: "https://twitter.com/isik_erenalp"
    - icon: fa-linkedin
      link: "https://tr.linkedin.com/in/isikerenalp"
    - icon: fa-github
      link: "https://github.com/isikerenalp"

# share:
#   twitter_username: github.io
#   fb_appid: 1749788565247320

urls:
    - text: Hakkımda
      url: /about/
    - text: XML Feed
      url: /feed.xml
    - text: Kaynak Önerileri
      url: /kaynak/

url: "https://isikerenalp.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
