# Site settings
title: Alp Eren Işık
description: Modern-Blog A Elegant template for Jekyll
keywords: Modern, Blogging, Fun
author: Alp Eren Işık
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://isikerenalp.me" # the base hostname & protocol for your site
