title:             Alp Eren Işık
description:       PauSiber
author:            Alp Eren Işık
baseurl:           ""
url:               "http://isikerenalp.me"

# Social Profiles
linkedin_username:  alp-eren-isik
github_username:   isikerenalp
dersim_username:   alperenisik

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
